# Try to match what Ruff Format does with Python code
tabWidth = 4
printWidth = 88
semi = true
singleQuote = false
trailingComma = "es5"
jsxSingleQuote = false
bracketSpacing = true
arrowParens = "always"
embeddedLanguageFormatting = "auto"
endOfLine = "lf"
insertPragma = false
proseWrap = "preserve"
quoteProps = "consistent"
requirePragma = false

[[overrides]]
files = ["*.tsx"]
options = { tabWidth = 2 }